[build]
  publish = "."
  command = ""

[functions]
  directory = "netlify/functions"


[[headers]]
  for = "/.netlify/functions/live-content"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
    CDN-Cache-Control = "no-store"
    Netlify-CDN-Cache-Control = "no-store"
