-- Adventure Sports Operations Hub V7.4.0
-- Run this once in a new Supabase project. Safe to rerun.
create extension if not exists pgcrypto;
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;

create table if not exists public.organizations(id uuid primary key default gen_random_uuid(),name text not null default 'Adventure Sports & Entertainment',timezone text not null default 'America/New_York',settings jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.roles(id uuid primary key default gen_random_uuid(),organization_id uuid references organizations(id) on delete cascade,name text not null,slug text not null,description text,is_system boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,slug));
create table if not exists public.permissions(id uuid primary key default gen_random_uuid(),key text unique not null,label text not null,module text not null,description text,created_at timestamptz not null default now());
create table if not exists public.role_permissions(role_id uuid references roles(id) on delete cascade,permission_id uuid references permissions(id) on delete cascade,allowed boolean not null default true,created_at timestamptz not null default now(),primary key(role_id,permission_id));
create table if not exists public.employees(id uuid primary key default gen_random_uuid(),organization_id uuid references organizations(id) on delete cascade,netlify_user_id uuid unique,email text unique not null,first_name text,last_name text,display_name text,phone text,role_slug text,status text not null default 'active' check(status in ('active','inactive','leave','terminated')),hire_date date,emergency_contact jsonb not null default '{}'::jsonb,notes text,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.employee_roles(employee_id uuid references employees(id) on delete cascade,role_id uuid references roles(id) on delete cascade,assigned_at timestamptz not null default now(),assigned_by uuid,primary key(employee_id,role_id));
create table if not exists public.employee_availability(id uuid primary key default gen_random_uuid(),employee_id uuid references employees(id) on delete cascade,day_of_week smallint check(day_of_week between 0 and 6),available_from time,available_to time,is_available boolean not null default true,effective_from date,effective_to date,notes text,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.time_off_requests(id uuid primary key default gen_random_uuid(),employee_id uuid references employees(id) on delete cascade,start_at timestamptz not null,end_at timestamptz not null,reason text,status text not null default 'pending' check(status in ('pending','approved','denied','cancelled')),reviewed_by uuid,reviewed_at timestamptz,review_notes text,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.shifts(id uuid primary key default gen_random_uuid(),employee_id uuid references employees(id) on delete set null,department text,position text,start_at timestamptz not null,end_at timestamptz not null,status text not null default 'scheduled',notes text,published_at timestamptz,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.shift_breaks(id uuid primary key default gen_random_uuid(),shift_id uuid references shifts(id) on delete cascade,start_at timestamptz,end_at timestamptz,paid boolean not null default false,created_at timestamptz not null default now());
create table if not exists public.certification_types(id uuid primary key default gen_random_uuid(),name text unique not null,description text,expires boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.employee_certifications(id uuid primary key default gen_random_uuid(),employee_id uuid references employees(id) on delete cascade,certification_type_id uuid references certification_types(id),issued_on date,expires_on date,document_path text,status text not null default 'valid',notes text,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.devices(id uuid primary key default gen_random_uuid(),employee_id uuid references employees(id) on delete set null,device_name text,platform text,push_token text,last_seen_at timestamptz,enabled boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create table if not exists public.fields(id uuid primary key default gen_random_uuid(),organization_id uuid references organizations(id) on delete cascade,code text unique not null,name text not null,sport text,surface_type text,status text not null default 'open',status_note text,dimensions jsonb not null default '{}'::jsonb,map_coordinates jsonb not null default '{}'::jsonb,sort_order integer not null default 0,active boolean not null default true,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.field_status_history(id uuid primary key default gen_random_uuid(),field_id uuid references fields(id) on delete cascade,status text not null,note text,effective_at timestamptz not null default now(),ended_at timestamptz,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.inspection_templates(id uuid primary key default gen_random_uuid(),name text not null,category text not null,description text,version integer not null default 1,active boolean not null default true,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.inspection_template_items(id uuid primary key default gen_random_uuid(),template_id uuid references inspection_templates(id) on delete cascade,label text not null,response_type text not null default 'condition',required boolean not null default true,options jsonb not null default '[]'::jsonb,sort_order integer not null default 0,created_at timestamptz not null default now());
create table if not exists public.field_inspections(id uuid primary key default gen_random_uuid(),field_id uuid references fields(id) on delete cascade,template_id uuid references inspection_templates(id) on delete set null,inspection_type text not null default 'opening',inspected_by uuid,started_at timestamptz default now(),completed_at timestamptz,overall_condition text,status text not null default 'in_progress',summary text,weather_snapshot jsonb not null default '{}'::jsonb,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.inspection_responses(id uuid primary key default gen_random_uuid(),inspection_id uuid references field_inspections(id) on delete cascade,template_item_id uuid references inspection_template_items(id) on delete set null,label text,response jsonb not null default '{}'::jsonb,condition text,notes text,requires_action boolean not null default false,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.field_maintenance_logs(id uuid primary key default gen_random_uuid(),field_id uuid references fields(id) on delete cascade,maintenance_type text not null,performed_at timestamptz not null default now(),performed_by uuid,quantity numeric,unit text,details jsonb not null default '{}'::jsonb,notes text,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.mound_configurations(id uuid primary key default gen_random_uuid(),field_id uuid references fields(id) on delete cascade,sport text,distance_feet numeric,mound_type text,installed_at timestamptz,removed_at timestamptz,condition text,notes text,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.base_configurations(id uuid primary key default gen_random_uuid(),field_id uuid references fields(id) on delete cascade,distance_feet numeric,configuration_name text,installed_at timestamptz,removed_at timestamptz,condition text,notes text,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create table if not exists public.maintenance_requests(id uuid primary key default gen_random_uuid(),title text not null,description text,location_type text,location_id uuid,priority text not null default 'normal',status text not null default 'new',requested_by uuid,assigned_to uuid,due_at timestamptz,completed_at timestamptz,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.work_orders(id uuid primary key default gen_random_uuid(),request_id uuid references maintenance_requests(id) on delete set null,work_order_number bigint generated by default as identity,title text not null,description text,category text,priority text not null default 'normal',status text not null default 'open',assigned_to uuid,scheduled_start timestamptz,scheduled_end timestamptz,completed_at timestamptz,labor_hours numeric not null default 0,cost numeric(12,2) not null default 0,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.work_order_tasks(id uuid primary key default gen_random_uuid(),work_order_id uuid references work_orders(id) on delete cascade,title text not null,completed boolean not null default false,completed_by uuid,completed_at timestamptz,sort_order integer not null default 0,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.preventive_maintenance_plans(id uuid primary key default gen_random_uuid(),asset_type text not null,asset_id uuid,title text not null,frequency text not null,next_due_at timestamptz,checklist jsonb not null default '[]'::jsonb,active boolean not null default true,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.equipment(id uuid primary key default gen_random_uuid(),asset_tag text unique,name text not null,category text,manufacturer text,model text,serial_number text,purchase_date date,purchase_cost numeric(12,2),status text not null default 'available',location text,meter_value numeric,warranty_expires_on date,notes text,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.equipment_assignments(id uuid primary key default gen_random_uuid(),equipment_id uuid references equipment(id) on delete cascade,employee_id uuid references employees(id) on delete set null,checked_out_at timestamptz not null default now(),due_back_at timestamptz,checked_in_at timestamptz,condition_out text,condition_in text,notes text,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.equipment_meter_logs(id uuid primary key default gen_random_uuid(),equipment_id uuid references equipment(id) on delete cascade,reading numeric not null,reading_type text,recorded_at timestamptz not null default now(),recorded_by uuid,notes text,created_at timestamptz not null default now());

create table if not exists public.vendors(id uuid primary key default gen_random_uuid(),name text unique not null,contact_name text,email text,phone text,address jsonb not null default '{}'::jsonb,website text,status text not null default 'active',notes text,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.inventory_categories(id uuid primary key default gen_random_uuid(),name text unique not null,department text,created_at timestamptz not null default now());
create table if not exists public.inventory_items(id uuid primary key default gen_random_uuid(),sku text unique,name text not null,category_id uuid references inventory_categories(id),vendor_id uuid references vendors(id) on delete set null,unit text not null default 'each',quantity_on_hand numeric not null default 0,reorder_point numeric not null default 0,reorder_quantity numeric not null default 0,unit_cost numeric(12,2),location text,barcode text,status text not null default 'active',created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.inventory_transactions(id uuid primary key default gen_random_uuid(),item_id uuid references inventory_items(id) on delete cascade,transaction_type text not null,quantity numeric not null,unit_cost numeric(12,2),reference_type text,reference_id uuid,notes text,performed_by uuid,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.inventory_counts(id uuid primary key default gen_random_uuid(),name text not null,status text not null default 'open',started_at timestamptz not null default now(),completed_at timestamptz,started_by uuid,completed_by uuid,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.inventory_count_items(id uuid primary key default gen_random_uuid(),count_id uuid references inventory_counts(id) on delete cascade,item_id uuid references inventory_items(id),expected_quantity numeric,counted_quantity numeric,variance numeric generated always as (coalesce(counted_quantity,0)-coalesce(expected_quantity,0)) stored,notes text,created_at timestamptz not null default now());
create table if not exists public.purchase_orders(id uuid primary key default gen_random_uuid(),po_number bigint generated by default as identity,vendor_id uuid references vendors(id),status text not null default 'draft',ordered_at timestamptz,expected_at timestamptz,received_at timestamptz,subtotal numeric(12,2) not null default 0,tax numeric(12,2) not null default 0,total numeric(12,2) not null default 0,notes text,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.purchase_order_items(id uuid primary key default gen_random_uuid(),purchase_order_id uuid references purchase_orders(id) on delete cascade,item_id uuid references inventory_items(id) on delete set null,description text not null,quantity numeric not null,unit_cost numeric(12,2) not null,received_quantity numeric not null default 0,created_at timestamptz not null default now());

create table if not exists public.tournaments(id uuid primary key default gen_random_uuid(),name text not null,organization_name text,start_date date not null,end_date date not null,sport text,status text not null default 'planning',contact jsonb not null default '{}'::jsonb,settings jsonb not null default '{}'::jsonb,notes text,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.teams(id uuid primary key default gen_random_uuid(),tournament_id uuid references tournaments(id) on delete cascade,name text not null,age_group text,division text,coach_name text,contact jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.games(id uuid primary key default gen_random_uuid(),tournament_id uuid references tournaments(id) on delete cascade,field_id uuid references fields(id) on delete set null,home_team_id uuid references teams(id) on delete set null,away_team_id uuid references teams(id) on delete set null,start_at timestamptz not null,end_at timestamptz,status text not null default 'scheduled',game_number text,division text,mound_distance numeric,base_distance numeric,score jsonb not null default '{}'::jsonb,notes text,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.game_assignments(id uuid primary key default gen_random_uuid(),game_id uuid references games(id) on delete cascade,employee_id uuid references employees(id) on delete set null,assignment_type text not null,notes text,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.tournament_field_blocks(id uuid primary key default gen_random_uuid(),tournament_id uuid references tournaments(id) on delete cascade,field_id uuid references fields(id) on delete cascade,start_at timestamptz not null,end_at timestamptz not null,reason text,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create table if not exists public.notifications(id uuid primary key default gen_random_uuid(),title text not null,message text not null,type text not null default 'general',priority text not null default 'normal',audience jsonb not null default '{}'::jsonb,scheduled_at timestamptz,sent_at timestamptz,status text not null default 'draft',created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.notification_receipts(id uuid primary key default gen_random_uuid(),notification_id uuid references notifications(id) on delete cascade,employee_id uuid references employees(id) on delete cascade,delivered_at timestamptz,read_at timestamptz,dismissed_at timestamptz,delivery_status text,unique(notification_id,employee_id));
create table if not exists public.notification_preferences(id uuid primary key default gen_random_uuid(),employee_id uuid references employees(id) on delete cascade unique,preferences jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.weather_observations(id uuid primary key default gen_random_uuid(),observed_at timestamptz not null,source text,temperature_f numeric,feels_like_f numeric,humidity numeric,wind_mph numeric,precipitation_in numeric,condition text,raw jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.weather_alerts(id uuid primary key default gen_random_uuid(),external_id text unique,event text,severity text,headline text,description text,effective_at timestamptz,expires_at timestamptz,raw jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());

create table if not exists public.rentals(id uuid primary key default gen_random_uuid(),customer_name text not null,customer_contact jsonb not null default '{}'::jsonb,rental_type text not null,resource_id uuid,start_at timestamptz not null,end_at timestamptz not null,status text not null default 'inquiry',amount numeric(12,2),deposit numeric(12,2),notes text,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.incident_reports(id uuid primary key default gen_random_uuid(),incident_number bigint generated by default as identity,occurred_at timestamptz not null,location text,incident_type text not null,severity text not null default 'minor',people_involved jsonb not null default '[]'::jsonb,description text not null,actions_taken text,status text not null default 'open',reported_by uuid,reviewed_by uuid,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.attachments(id uuid primary key default gen_random_uuid(),entity_type text not null,entity_id uuid not null,bucket text not null,storage_path text not null,file_name text not null,mime_type text,file_size bigint,uploaded_by uuid,created_at timestamptz not null default now());
create table if not exists public.comments(id uuid primary key default gen_random_uuid(),entity_type text not null,entity_id uuid not null,body text not null,author_id uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.activity_feed(id uuid primary key default gen_random_uuid(),entity_type text,entity_id uuid,action text not null,summary text,actor_id uuid,metadata jsonb not null default '{}'::jsonb,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.audit_logs(id uuid primary key default gen_random_uuid(),actor_id uuid,actor_email text,action text not null,entity_type text,entity_id uuid,before_data jsonb,after_data jsonb,ip_address inet,user_agent text,created_at timestamptz not null default now());

create table if not exists public.website_settings(id uuid primary key default gen_random_uuid(),key text unique not null,value jsonb not null default '{}'::jsonb,published_at timestamptz,published_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.website_announcements(id uuid primary key default gen_random_uuid(),title text,message text not null,status text not null default 'draft',starts_at timestamptz,ends_at timestamptz,published_at timestamptz,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.content_revisions(id uuid primary key default gen_random_uuid(),content_key text not null,revision integer not null,data jsonb not null,created_by uuid,created_at timestamptz not null default now(),unique(content_key,revision));
create table if not exists public.clover_daily_summaries(id uuid primary key default gen_random_uuid(),business_date date unique not null,gross_sales numeric(12,2),net_sales numeric(12,2),tax numeric(12,2),tips numeric(12,2),refunds numeric(12,2),orders_count integer,raw jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.clover_transactions(id uuid primary key default gen_random_uuid(),external_id text unique not null,occurred_at timestamptz,employee_external_id text,amount numeric(12,2),tip numeric(12,2),tax numeric(12,2),status text,raw jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.reports(id uuid primary key default gen_random_uuid(),name text not null,report_type text not null,parameters jsonb not null default '{}'::jsonb,result_path text,status text not null default 'queued',generated_by uuid,generated_at timestamptz,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.saved_views(id uuid primary key default gen_random_uuid(),employee_id uuid references employees(id) on delete cascade,module text not null,name text not null,filters jsonb not null default '{}'::jsonb,columns jsonb not null default '[]'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.integrations(id uuid primary key default gen_random_uuid(),provider text unique not null,status text not null default 'disconnected',settings jsonb not null default '{}'::jsonb,last_sync_at timestamptz,last_error text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.integration_sync_logs(id uuid primary key default gen_random_uuid(),integration_id uuid references integrations(id) on delete cascade,started_at timestamptz not null default now(),finished_at timestamptz,status text not null default 'running',records_processed integer not null default 0,error text,details jsonb not null default '{}'::jsonb); 
create table if not exists public.export_history(id uuid primary key default gen_random_uuid(),export_type text not null,parameters jsonb not null default '{}'::jsonb,file_path text,status text not null default 'queued',requested_by uuid,completed_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.backup_history(id uuid primary key default gen_random_uuid(),backup_type text not null,status text not null default 'queued',storage_path text,started_at timestamptz not null default now(),completed_at timestamptz,error text,requested_by uuid,created_at timestamptz not null default now());
create table if not exists public.app_settings(id uuid primary key default gen_random_uuid(),key text unique not null,value jsonb not null default '{}'::jsonb,visibility text not null default 'owner',created_at timestamptz not null default now(),updated_at timestamptz not null default now());

-- Consistent update timestamps.
do $$ declare r record; begin for r in select tablename from pg_tables where schemaname='public' and tablename not in ('permissions','role_permissions','shift_breaks','certification_types','inspection_template_items','equipment_meter_logs','inventory_categories','inventory_count_items','purchase_order_items','teams','notification_receipts','weather_alerts','attachments','audit_logs','content_revisions','clover_transactions','integration_sync_logs','export_history','backup_history') loop execute format('drop trigger if exists set_updated_at on public.%I',r.tablename); execute format('create trigger set_updated_at before update on public.%I for each row execute function public.set_updated_at()',r.tablename); end loop; end $$;

-- Service-role-only browser security. Netlify Functions use the service role and enforce app roles.
do $$ declare r record; begin for r in select tablename from pg_tables where schemaname='public' loop execute format('alter table public.%I enable row level security',r.tablename); end loop; end $$;

-- Helpful indexes.
create index if not exists idx_shifts_start on shifts(start_at);
create index if not exists idx_games_start_field on games(start_at,field_id);
create index if not exists idx_inspections_field_created on field_inspections(field_id,created_at desc);
create index if not exists idx_work_orders_status on work_orders(status,priority);
create index if not exists idx_inventory_low on inventory_items(quantity_on_hand,reorder_point);
create index if not exists idx_notifications_status_schedule on notifications(status,scheduled_at);
create index if not exists idx_activity_created on activity_feed(created_at desc);
create index if not exists idx_audit_created on audit_logs(created_at desc);

-- Storage buckets (private by default).
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values
('inspection-photos','inspection-photos',false,15728640,array['image/jpeg','image/png','image/webp']),
('incident-files','incident-files',false,26214400,array['image/jpeg','image/png','image/webp','application/pdf']),
('employee-documents','employee-documents',false,26214400,array['application/pdf','image/jpeg','image/png']),
('report-exports','report-exports',false,52428800,array['application/pdf','text/csv','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'])
on conflict(id) do update set file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
