(function(){
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const app=$('#app'),gate=$('#loginGate'),sidebar=$('#sidebar'),AUTH_KEY='ase_ops_identity_session_v1',IDENTITY='/.netlify/identity',LIVE='/.netlify/functions/live-content?file=site',PUBLISH='/.netlify/functions/publish-content';
let deferredPrompt=null,session=null,siteData=null,originalStatus='',originalAnnouncement='',publishing=false;
function displayName(u){const m=u?.user_metadata||{},raw=m.full_name||m.name||m.display_name||'';if(raw.trim())return raw.trim().split(/\s+/)[0];if(u?.email)return u.email.split('@')[0].replace(/[._-]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase());return'Administrator'}
function greeting(){const h=new Date().getHours();return h<12?'Good Morning':h<17?'Good Afternoon':'Good Evening'}
function renderUser(u){const n=displayName(u);$('#greeting').textContent=greeting();$('#userName').textContent=n;$('#accountEmail').textContent=u?.email||'Signed-in administrator';$('#publisherEmail').textContent=u?.email||'Administrator';$$('.avatar').forEach(x=>x.textContent=n[0].toUpperCase())}
function showApp(u){gate.hidden=true;app.hidden=false;renderUser(u);loadSite()}
function showGate(){app.hidden=true;gate.hidden=false}
function loginStatus(m,t=''){const e=$('#loginStatus');e.textContent=m;e.className='login-status'+(t?' '+t:'')}
function saveSession(token,user){session={token,user,saved_at:Date.now()};localStorage.setItem(AUTH_KEY,JSON.stringify(session))}
function clearSession(){session=null;localStorage.removeItem(AUTH_KEY)}
function readSession(){try{return JSON.parse(localStorage.getItem(AUTH_KEY)||'null')}catch{return null}}
async function fetchUser(token){const r=await fetch(IDENTITY+'/user',{headers:{Authorization:'Bearer '+token},cache:'no-store'});if(!r.ok)throw Error('Your login session could not be verified.');return r.json()}
async function refreshSession(s){if(!s?.token?.refresh_token)return null;const body=new URLSearchParams({grant_type:'refresh_token',refresh_token:s.token.refresh_token}),r=await fetch(IDENTITY+'/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)return null;const token=await r.json(),user=await fetchUser(token.access_token);saveSession(token,user);return session}
async function ensureSession(){if(session?.token?.access_token)return session;const s=readSession();if(!s)return null;try{const u=await fetchUser(s.token.access_token);saveSession(s.token,u);return session}catch{return refreshSession(s)}}
async function restoreSession(){showGate();const s=readSession();if(!s?.token){loginStatus('Enter the email and password used for the website admin.');return}try{const u=await fetchUser(s.token.access_token);saveSession(s.token,u);showApp(u)}catch{const fresh=await refreshSession(s).catch(()=>null);if(fresh)showApp(fresh.user);else{clearSession();loginStatus('Your session expired. Please sign in again.')}}}
async function login(email,password){const body=new URLSearchParams({grant_type:'password',username:email,password}),r=await fetch(IDENTITY+'/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error_description||d.msg||d.error||'The email or password is incorrect.');const u=await fetchUser(d.access_token);saveSession(d,u);return u}
async function handleLogin(e){e.preventDefault();const email=$('#loginEmail'),pw=$('#loginPassword'),b=$('#loginButton');if(!email.validity.valid||!pw.value){loginStatus('Enter a valid email address and password.','error');return}b.disabled=true;b.textContent='Signing In…';loginStatus('Checking your account securely…','loading');try{showApp(await login(email.value.trim(),pw.value))}catch(err){loginStatus(err.message||'Sign-in failed.','error')}finally{b.disabled=false;b.textContent='Sign In'}}
function logout(){clearSession();showGate();$('#loginPassword').value='';loginStatus('You have been signed out.','success')}
function go(v){$$('.view').forEach(x=>x.classList.toggle('active',x.dataset.viewPanel===v));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));sidebar.classList.remove('open');history.replaceState(null,'','#'+v);window.scrollTo({top:0,behavior:'smooth'});if(v==='website'&&!siteData)loadSite()}
async function liveSite(){const r=await fetch(LIVE+'&v='+Date.now(),{cache:'no-store'});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||`Unable to load website controls (${r.status}).`);return d}
async function loadSite(){setEditor('Loading','loading');try{siteData=await liveSite();applyLoaded();setEditor('Live','ready')}catch(err){console.error(err);try{const r=await fetch('/content/site.json?ops='+Date.now(),{cache:'no-store'});if(!r.ok)throw err;siteData=await r.json();applyLoaded();setEditor('Published copy','warning');notice('Live data could not be reached. The last deployed copy is shown.','warning')}catch{setEditor('Unavailable','error');notice(err.message||'Website controls could not be loaded.','error')}}}
function applyLoaded(){originalStatus=siteData.fieldStatus||'OPEN';originalAnnouncement=siteData.announcement||'';const radio=$(`input[name="fieldStatus"][value="${CSS.escape(originalStatus)}"]`)||$('input[value="OPEN"]');if(radio)radio.checked=true;$('#announcementInput').value=originalAnnouncement;$('#currentLiveStatus').textContent=originalStatus;$('#lastLoadedTime').textContent=new Date().toLocaleString();updatePreview();updateDashboard()}
function currentStatus(){return $('input[name="fieldStatus"]:checked')?.value||'OPEN'}
function updateDashboard(){if(!siteData)return;$('#facilityStatus').textContent=siteData.fieldStatus||'OPEN';$('#dashboardLiveDot').dataset.status=(siteData.fieldStatus||'OPEN').toLowerCase().replace(/\s+/g,'-')}
function dirty(){return currentStatus()!==originalStatus||$('#announcementInput').value.trim()!==originalAnnouncement.trim()}
function updatePreview(){const s=currentStatus(),a=$('#announcementInput').value.trim()||'No announcement is currently posted.',key=s.toLowerCase().replace(/\s+/g,'-');$('#previewStatus').textContent=s;$('#previewAnnouncement').textContent=a;$('#previewDot').dataset.status=key;$('#sitePreview').dataset.status=key;$('#announcementCount').textContent=`${$('#announcementInput').value.length} / 240`;const d=dirty();$('#changeState').textContent=d?'Ready to publish':'None';$('#changeState').className=d?'has-changes':'';$('#publishControlsButton').disabled=!d||publishing;$('#resetControlsButton').disabled=!d||publishing}
function setEditor(t,c=''){const e=$('#editorState');e.textContent=t;e.className='connection-badge'+(c?' '+c:'')}
function notice(m,t='success'){const e=$('#publishNotice');e.textContent=m;e.className='publish-notice '+t;e.hidden=false}
function hideNotice(){$('#publishNotice').hidden=true}
async function publish(e){e.preventDefault();hideNotice();if(!siteData||publishing)return;const announcement=$('#announcementInput').value.trim();if(!announcement){notice('Please enter a homepage announcement before publishing.','error');return}const s=await ensureSession();if(!s){notice('Your session expired. Please sign in again.','error');return}publishing=true;setEditor('Publishing','loading');const btn=$('#publishControlsButton');btn.textContent='Publishing…';updatePreview();try{const r=await fetch(PUBLISH,{method:'POST',headers:{Authorization:'Bearer '+s.token.access_token,'Content-Type':'application/json'},body:JSON.stringify({fieldStatus:currentStatus(),announcement})});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||`Publishing failed (${r.status}).`);siteData=d.site;originalStatus=siteData.fieldStatus;originalAnnouncement=siteData.announcement;$('#currentLiveStatus').textContent=originalStatus;updateDashboard();setEditor('Live now','ready');notice('Live update published. Visitors will see it immediately when the page loads or refreshes. /admin will show it after you refresh that page.','success');toast('Website updated live')}catch(err){console.error(err);setEditor('Publish failed','error');notice(err.message||'The website update could not be published.','error')}finally{publishing=false;btn.textContent='Publish to Website';updatePreview()}}
function reset(){if(!siteData)return;applyLoaded();hideNotice();toast('Changes reset')}
function install(){if(deferredPrompt){deferredPrompt.prompt();deferredPrompt.userChoice.finally(()=>deferredPrompt=null)}else toast('On iPhone: Safari → Share → Add to Home Screen')}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3500)}
$$('.nav-item').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));$('#menuButton').addEventListener('click',()=>sidebar.classList.toggle('open'));$('#loginForm').addEventListener('submit',handleLogin);$('#logoutButton').addEventListener('click',logout);$('#settingsLogout').addEventListener('click',logout);$('#installButton').addEventListener('click',install);$('#settingsInstall').addEventListener('click',install);$('#quickControlsForm').addEventListener('submit',publish);$('#resetControlsButton').addEventListener('click',reset);$$('input[name="fieldStatus"]').forEach(x=>x.addEventListener('change',updatePreview));$('#announcementInput').addEventListener('input',updatePreview);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installButton').hidden=false});window.addEventListener('beforeunload',e=>{if(dirty()){e.preventDefault();e.returnValue=''}});
if('serviceWorker'in navigator){navigator.serviceWorker.getRegistrations().then(rs=>rs.filter(r=>r.scope.includes('/ops/')).forEach(r=>r.unregister())).catch(()=>{});if(window.caches)caches.keys().then(ks=>ks.filter(k=>k.startsWith('ase-ops-')).forEach(k=>caches.delete(k))).catch(()=>{})}const initial=location.hash.replace('#','');if(initial&&$(`[data-view-panel="${initial}"]`))go(initial);restoreSession();
})();