(function(){
'use strict';
const $=s=>document.querySelector(s);
const STORE='ase-ops73-checklist-v1';
const tasks=['Opening walk-through complete','All active fields checked','Front gate and clubhouse ready','Staff coverage confirmed','Weather and radar reviewed','Emergency exits and first aid checked','Closing manager assigned'];
let schedule={"2026-07-28":{"games":50,"first":"8:00 AM","last":"8:00 PM","fields":8},"2026-07-29":{"games":31,"first":"10:00 AM","last":"4:00 PM","fields":8},"2026-07-30":{"games":13,"first":"8:30 AM","last":"6:30 PM","fields":4},"2026-07-31":{"games":24,"first":"3:00 PM","last":"7:00 PM","fields":8},"2026-08-01":{"games":47,"first":"9:00 AM","last":"7:00 PM","fields":8},"2026-08-02":{"games":33,"first":"8:45 AM","last":"5:00 PM","fields":7},"2026-08-03":{"games":13,"first":"8:15 AM","last":"6:45 PM","fields":4}};
function iso(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function clock(){const d=new Date(); $('#ops73Clock').textContent=d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}); $('#ops73Date').textContent=d.toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'}); $('#ops73DateLine').textContent=d.toLocaleDateString([],{weekday:'long',month:'long',day:'numeric',year:'numeric'})+' • Live facility overview';}
async function weather(){try{const r=await fetch('https://api.open-meteo.com/v1/forecast?latitude=40.0912&longitude=-74.3587&current=temperature_2m,apparent_temperature,weather_code,precipitation,wind_speed_10m&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=America%2FNew_York',{cache:'no-store'});const d=await r.json(),c=d.current||{};const code=Number(c.weather_code);const label=code===0?'Clear':code<=3?'Partly cloudy':code<=67?'Rain possible':code<=77?'Snow':code<=82?'Rain showers':'Storm risk';$('#ops73Temp').textContent=Math.round(c.temperature_2m)+'°F';$('#ops73WeatherText').textContent=label+' • Feels '+Math.round(c.apparent_temperature)+'°';$('#ops73WeatherIcon').textContent=code===0?'☀':code<=3?'⛅':code<=82?'🌧':'⛈';}catch{$('#ops73Temp').textContent='Open Weather';$('#ops73WeatherText').textContent='Tap for live conditions';}}
function applyMatrix(matrix){if(!matrix?.days)return;schedule={};matrix.days.forEach(day=>{const fields=new Set(day.rows.flatMap(r=>r[1]));schedule[day.key]={games:day.rows.reduce((n,r)=>n+r[1].length,0),first:day.rows[0]?.[0]||'—',last:day.rows.at(-1)?.[0]||'—',fields:fields.size}});games()}
function games(){const d=schedule[iso()]||{games:0,first:'—',last:'—',fields:0};$('#ops73Games').textContent=d.games;$('#ops73GamesNote').textContent=d.games?d.fields+' fields active':'No tournament schedule today';$('#ops73FirstGame').textContent=d.first;$('#ops73LastGame').textContent=d.last;$('#ops73Fields').textContent=d.fields+' / 8';const times=d.games?['Opening crew on site','First pitch '+d.first,'Peak field operations','Final scheduled start '+d.last,'Closing walk-through']:['Facility operations day','Review events and rentals','Complete maintenance priorities'];$('#ops73Timeline').innerHTML=times.map((x,i)=>`<div class="ops73-timeline-row"><span>${i+1}</span><div><b>${x}</b><small>${i===0?'Start-of-day readiness':i===times.length-1?'End-of-day handoff':'Live operations milestone'}</small></div></div>`).join('');}
function maintenance(){try{const s=JSON.parse(localStorage.getItem('ase-maintenance-operations-v1')||'{}');const issues=(s.issues||[]).filter(x=>x.status!=='resolved');const fields=Object.values(s.fields||{}).filter(x=>x.status==='attention'||x.status==='urgent');const n=issues.length+fields.length;$('#ops73Maintenance').textContent=n;$('#ops73MaintenanceNote').textContent=n?`${n} item${n===1?'':'s'} need attention`:'All fields ready';}catch{$('#ops73Maintenance').textContent='0';$('#ops73MaintenanceNote').textContent='All fields ready';}}
function staff(){setTimeout(()=>{const count=$('#staffWorkingCount')?.textContent||'—';const close=$('#staffClosingTime')?.textContent||'View staff';$('#ops73Staff').textContent=count;$('#ops73StaffNote').textContent=count==='—'?'Open Staff Command Center':'currently scheduled';$('#ops73Closing').textContent=close;},1200)}
function state(){const key=iso();const all=JSON.parse(localStorage.getItem(STORE)||'{}');return {all,key,done:all[key]||[]}}
function checklist(){const {done}=state();$('#ops73Checklist').innerHTML=tasks.map((t,i)=>`<label class="ops73-task ${done.includes(i)?'done':''}"><input type="checkbox" data-task="${i}" ${done.includes(i)?'checked':''}><span>✓</span><b>${t}</b></label>`).join('');const pct=Math.round(done.length/tasks.length*100);$('#ops73ChecklistProgress').textContent=pct+'%';$('#ops73ChecklistBar').style.width=pct+'%';}
function toggle(i,on){const {all,key,done}=state();const set=new Set(done);on?set.add(i):set.delete(i);all[key]=[...set];localStorage.setItem(STORE,JSON.stringify(all));checklist()}
function emergency(){const btn=$('[data-go="notifications"]');btn?.click();setTimeout(()=>{const title=$('#notificationTitle');const body=$('#notificationBody');if(title&&!title.value)title.value='Emergency Operations Alert';if(body&&!body.value)body.value='Important facility alert. Follow manager instructions immediately and check the Operations Hub for updates.';},150)}
function init(){if(!$('#ops73Clock'))return;clock();setInterval(clock,30000);weather();games();window.addEventListener('ase:matrix-updated',e=>applyMatrix(e.detail));maintenance();staff();checklist();$('#ops73Checklist').addEventListener('change',e=>{if(e.target.matches('[data-task]'))toggle(Number(e.target.dataset.task),e.target.checked)});$('#ops73ResetChecklist').addEventListener('click',()=>{const {all,key}=state();delete all[key];localStorage.setItem(STORE,JSON.stringify(all));checklist()});$('#ops73Emergency').addEventListener('click',emergency);window.addEventListener('storage',maintenance);}
document.addEventListener('DOMContentLoaded',init);
})();
