(function(){'use strict';
const modules={employees:'Employees',fields:'Fields',incident_reports:'Incident Reports',maintenance_requests:'Maintenance Requests',work_orders:'Work Orders',equipment:'Equipment',inventory_items:'Inventory',tournaments:'Tournaments',games:'Games',notifications:'Notifications',reports:'Reports',website_announcements:'Website Announcements'};
const hidden=new Set(['created_by','updated_by','reported_by','reviewed_by','organization_id']);
const readonly=new Set(['id','created_at','updated_at','incident_number']);
const $=s=>document.querySelector(s);let table='incident_reports',rows=[],offset=0,limit=50,editing=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const label=k=>k.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const role=()=>document.body.dataset.role||window.ASE_OPS?.role?.();
function notice(msg,bad=false){const n=$('#databaseNotice');if(!n)return;n.textContent=msg;n.className='publish-notice '+(bad?'error':'success');n.hidden=false;setTimeout(()=>n.hidden=true,5000)}
function display(v){if(v===null||v===undefined||v==='')return '—';if(typeof v==='object')return JSON.stringify(v);if(typeof v==='boolean')return v?'Yes':'No';return String(v)}
function visibleColumns(){const keys=new Set();rows.forEach(r=>Object.keys(r).forEach(k=>!hidden.has(k)&&keys.add(k)));const preferred=['incident_number','name','title','occurred_at','location','incident_type','severity','status','description','active'];return [...keys].sort((a,b)=>(preferred.indexOf(a)<0?99:preferred.indexOf(a))-(preferred.indexOf(b)<0?99:preferred.indexOf(b))).slice(0,7)}
function render(){const q=($('#databaseSearch')?.value||'').toLowerCase();const shown=rows.filter(r=>!q||Object.values(r).some(v=>display(v).toLowerCase().includes(q)));const cols=visibleColumns();$('#databaseHead').innerHTML='<tr>'+cols.map(c=>'<th>'+esc(label(c))+'</th>').join('')+'<th>Actions</th></tr>';$('#databaseBody').innerHTML=shown.length?shown.map(r=>'<tr>'+cols.map(c=>'<td title="'+esc(display(r[c]))+'">'+esc(display(r[c])).slice(0,120)+'</td>').join('')+'<td><button class="secondary-btn compact-btn" data-db-edit="'+esc(r.id)+'">Edit</button></td></tr>').join(''):'<tr><td colspan="'+(cols.length+1)+'" class="empty-row">No records found.</td></tr>';$('#databaseCount').textContent=shown.length+' record'+(shown.length===1?'':'s');$$('[data-db-edit]').forEach(b=>b.onclick=()=>open(rows.find(r=>r.id===b.dataset.dbEdit)))}
const $$=s=>[...document.querySelectorAll(s)];
async function load(){if(role()!=='owner')return;$('#databaseHealth').textContent='Loading';$('#databaseHealth').className='connection-badge loading';try{const d=await ASE_DATA.list(table,{limit,offset});rows=d.rows||[];render();$('#databaseHealth').textContent='Connected';$('#databaseHealth').className='connection-badge ready'}catch(e){notice(e.message,true);$('#databaseHealth').textContent='Error';$('#databaseHealth').className='connection-badge error'}}
function input(k,v){if(hidden.has(k)||readonly.has(k))return '';const val=v===null||v===undefined?'':(typeof v==='object'?JSON.stringify(v,null,2):String(v));const type=/(_at|date|time)$/.test(k)?'datetime-local':(/description|notes|statement|people_involved|actions_taken|content/.test(k)?'textarea':'input');if(type==='textarea')return '<label><span>'+esc(label(k))+'</span><textarea name="'+esc(k)+'" rows="4">'+esc(val)+'</textarea></label>';return '<label><span>'+esc(label(k))+'</span><input name="'+esc(k)+'" value="'+esc(val)+'"></label>'}
function open(row){editing=row||null;$('#databaseModalTitle').textContent=(row?'Edit ':'Add ')+modules[table];const source=row||({status:'open'});let fields=Object.keys(source).filter(k=>!hidden.has(k)&&!readonly.has(k));if(!row){const templates={incident_reports:['occurred_at','location','incident_type','severity','people_involved','description','actions_taken','status'],fields:['name','status','notes'],employees:['first_name','last_name','email','phone','active'],maintenance_requests:['title','description','priority','status'],work_orders:['title','description','priority','status'],equipment:['name','status','notes'],inventory_items:['name','quantity','reorder_level','unit'],tournaments:['name','start_date','end_date','status'],games:['game_date','start_time','home_team','away_team','status'],notifications:['title','message','status'],reports:['title','report_type','status'],website_announcements:['title','message','active']};fields=templates[table]||['name','status']}
 $('#databaseForm').innerHTML='<div class="database-form-grid">'+fields.map(k=>input(k,source[k])).join('')+'</div><div class="form-actions">'+(row?'<button class="warning-btn" id="databaseDelete" type="button">Delete</button>':'')+'<button class="secondary-btn" type="button" data-db-close>Cancel</button><button class="primary-btn" type="submit">Save Record</button></div>';$('#databaseModal').hidden=false;document.body.classList.add('modal-open');$$('[data-db-close]').forEach(x=>x.onclick=close);$('#databaseDelete')?.addEventListener('click',remove)}
function close(){ $('#databaseModal').hidden=true;document.body.classList.remove('modal-open') }
async function save(e){e.preventDefault();const data={};new FormData(e.target).forEach((v,k)=>{v=String(v).trim();if(v==='')return;if(k==='people_involved'){try{data[k]=JSON.parse(v)}catch{data[k]=v}}else data[k]=v});try{editing?await ASE_DATA.update(table,editing.id,data):await ASE_DATA.create(table,data);close();notice('Record saved.');load()}catch(err){notice(err.message,true)}}
async function remove(){if(!editing||!confirm('Delete this record? This cannot be undone.'))return;try{await ASE_DATA.remove(table,editing.id);close();notice('Record deleted.');load()}catch(e){notice(e.message,true)}}
function init(){if(role()!=='owner')return;const select=$('#databaseTableSelect');if(!select)return;select.innerHTML=Object.entries(modules).map(([k,v])=>'<option value="'+k+'">'+v+'</option>').join('');select.value=table;$('#databaseCards').innerHTML=Object.entries(modules).slice(0,8).map(([k,v])=>'<button data-db-table="'+k+'"><span>▦</span><b>'+v+'</b><small>Open records</small></button>').join('');select.onchange=()=>{table=select.value;offset=0;load()};$('#databaseRefresh').onclick=load;$('#databaseSearch').oninput=render;$('#databaseAdd').onclick=()=>open(null);$('#databasePrev').onclick=()=>{offset=Math.max(0,offset-limit);load()};$('#databaseNext').onclick=()=>{offset+=limit;load()};$('#databaseForm').onsubmit=save;$$('[data-db-table]').forEach(b=>b.onclick=()=>{table=b.dataset.dbTable;select.value=table;offset=0;load()});load()}
window.addEventListener('ase:profile-ready',()=>setTimeout(init,100));document.addEventListener('DOMContentLoaded',()=>setTimeout(init,900));
})();
