(()=>{
'use strict';
const STANDARD_FIELDS=['A1','A2','B1','B2','C1','C2','D1','D2'];
const TZ='America/New_York',API='/.netlify/functions/tournament-matrix';
const FALLBACK={"id":"cup-championship-2026","name":"Tournament Field Matrix","dateRange":"July 28–August 3, 2026","fields":["A1","A2","B1","B2","C1","C2","D1","D2"],"days":[{"key":"2026-08-03","label":"Monday","short":"Mon · Aug 3","rows":[["8:15 AM",["A2","C1"]],["8:30 AM",["B2"]],["10:45 AM",["A2","C1"]],["11:15 AM",["B2"]],["1:15 PM",["A2","B1"]],["1:45 PM",["B2"]],["3:45 PM",["A2","B1"]],["4:15 PM",["B2"]],["6:45 PM",["B2"]]]}],"status":"published","version":1};
const SETUPS=[
 {field:'A1',division:'11U',pitch:"50'",bases:"70'",note:'Change to 12U after Thursday semifinals only if needed.'},{field:'A2',division:'11U → 12U',pitch:"50'",bases:"70'",note:'11U Tuesday through Thursday morning. 12U Thursday afternoon through championship.',warn:true},{field:'B1',division:'12U',pitch:"50'",bases:"70'",note:'No changes all week.'},{field:'B2',division:'12U Championship',pitch:"50'",bases:"70'",note:'Championship field. No changes all week.',champ:true},{field:'C1',division:'10U',pitch:"46'",bases:"65'",note:'No changes all week.'},{field:'C2',division:'8U → 9U',pitch:"Coach Pitch → 46'",bases:"65'",note:'Install mound and convert from coach pitch to 9U when scheduled.',warn:true,critical:true},{field:'D1',division:'10U → 9U',pitch:"46'",bases:"65'",note:'Division change keeps mound and bases in place.'},{field:'D2',division:'9U',pitch:"46'",bases:"65'",note:'No changes all week.'}
];
let matrix=FALLBACK,current=FALLBACK,library=[],archive=[],active=0,editor=null,editorDay=0,dirty=false,canManage=false;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const clone=v=>JSON.parse(JSON.stringify(v));
const total=d=>(d?.rows||[]).reduce((n,r)=>n+(r[1]||[]).length,0);
const isoToday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const todayIndex=()=>{const i=(matrix.days||[]).findIndex(d=>d.key===isoToday());return i>=0?i:0};
const role=()=>window.ASE_OPS?.role?.()||'cashier';
function session(){try{return JSON.parse(localStorage.getItem('ase_ops_identity_session_v2')||'null')}catch{return null}}
async function request(options={}){const api=window.ASE_OPS?.api;if(api)return api(API,options);const token=session()?.token?.access_token;const r=await fetch(API,{cache:'no-store',...options,headers:{Authorization:'Bearer '+token,...(options.headers||{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Matrix request failed.');return d}
function apiPost(payload){return request({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})}
function dayMeta(key){const d=new Date(`${key}T12:00:00Z`);return{label:d.toLocaleDateString('en-US',{weekday:'long',timeZone:'UTC'}),short:d.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric',timeZone:'UTC'}).replace(',',' ·')}}
function dateRange(days){if(!days?.length)return'No dates selected';const sorted=[...days].sort((a,b)=>a.key.localeCompare(b.key)),a=new Date(sorted[0].key+'T12:00:00Z'),b=new Date(sorted.at(-1).key+'T12:00:00Z');return`${a.toLocaleDateString('en-US',{month:'long',day:'numeric',timeZone:'UTC'})}–${b.toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'})}`}
function to24(time){const m=String(time||'').match(/(\d+):(\d+)\s*(AM|PM)/i);if(!m)return'09:00';let h=Number(m[1])%12;if(m[3].toUpperCase()==='PM')h+=12;return`${String(h).padStart(2,'0')}:${m[2]}`}
function to12(value){const m=String(value||'').match(/^(\d{1,2}):(\d{2})$/);if(!m)return'9:00 AM';let h=Number(m[1]),ampm=h>=12?'PM':'AM';h=h%12||12;return`${h}:${m[2]} ${ampm}`}
function offsetFor(key){const p=new Intl.DateTimeFormat('en-US',{timeZone:TZ,timeZoneName:'longOffset'}).formatToParts(new Date(`${key}T12:00:00Z`));return(p.find(x=>x.type==='timeZoneName')?.value||'GMT-04:00').replace('GMT','')}
function parseTime(key,time){return new Date(`${key}T${to24(time)}:00${offsetFor(key)}`)}
function currentStatus(day,rowIndex){if(day.key!==isoToday())return'scheduled';const now=new Date(),start=parseTime(day.key,day.rows[rowIndex][0]),end=new Date(start.getTime()+105*60000);return now>=start&&now<end?'live':now>=end?'finished':'upcoming'}
function fieldGameCount(day,field){return(day.rows||[]).filter(r=>(r[1]||[]).includes(field)).length}
function nextFieldGame(day,field){const rows=(day.rows||[]).filter(r=>(r[1]||[]).includes(field));if(day.key!==isoToday())return rows[0]?.[0]||'—';const now=new Date(),r=rows.find(x=>parseTime(day.key,x[0])>=now);return r?.[0]||'Complete'}
function markDirty(on=true){dirty=on;const b=$('#gamesSaveDraftButton');if(b)b.textContent=on?'Save Draft •':'Save Draft';const state=$('#gamesEditorState');if(state){state.textContent=on?'Unsaved changes':editor?.status==='published'?'Published':'Draft';state.className='connection-badge '+(on?'loading':editor?.status==='published'?'ready':'neutral')}}
function notice(message,type='success'){const el=$('#gamesMatrixNotice');if(!el)return;el.textContent=message;el.className='publish-notice '+type;el.hidden=false}

function renderTabs(){const box=$('#gamesDayTabs');if(!box)return;box.innerHTML=(matrix.days||[]).map((d,i)=>`<button type="button" class="games-day-tab ${i===active?'active':''}" data-day="${i}"><span>${esc(d.label)}</span><small>${esc((d.short||'').split('·')[1]?.trim()||d.key)}</small></button>`).join('');$$('button',box).forEach(b=>b.onclick=()=>{active=Number(b.dataset.day);renderOverview()})}
function renderSummary(day){if(!day)return;const unique=new Set((day.rows||[]).flatMap(r=>r[1]||[])).size,first=day.rows?.[0]?.[0]||'—',last=day.rows?.at(-1)?.[0]||'—',today=day.key===isoToday();const selected=$('#gamesSelectedDay');if(selected)selected.textContent=`${day.label} · ${new Date(day.key+'T12:00:00Z').toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'})}`;const box=$('#gamesSummary');if(box)box.innerHTML=`<article class="games-summary-card"><span>Games Scheduled</span><strong>${total(day)}</strong><small>${today?'Today':'Selected day'}</small></article><article class="games-summary-card"><span>Fields Used</span><strong>${unique} / ${(matrix.fields||STANDARD_FIELDS).length}</strong><small>${Math.max(0,(matrix.fields||STANDARD_FIELDS).length-unique)} field${Math.max(0,(matrix.fields||STANDARD_FIELDS).length-unique)===1?'':'s'} idle</small></article><article class="games-summary-card"><span>First Pitch</span><strong>${first}</strong><small>Opening start time</small></article><article class="games-summary-card"><span>Last Start</span><strong>${last}</strong><small>Final scheduled slot</small></article>`}
function renderMatrix(day){const box=$('#gamesMatrix');if(!box||!day)return;const fields=matrix.fields||STANDARD_FIELDS;box.innerHTML=`<table class="games-matrix"><thead><tr><th>Time</th>${fields.map(f=>`<th>${f}</th>`).join('')}<th>Total</th></tr></thead><tbody>${(day.rows||[]).map(([time,used],idx)=>{const status=currentStatus(day,idx);return`<tr class="games-row ${status}"><td><div class="games-time-cell"><strong>${esc(time)}</strong>${status==='live'?'<span class="live-pill">LIVE</span>':status==='finished'?'<span class="done-pill">DONE</span>':''}</div></td>${fields.map(f=>`<td><span class="game-slot ${(used||[]).includes(f)?'active':'empty'}">${(used||[]).includes(f)?'✓':'—'}</span></td>`).join('')}<td><strong>${(used||[]).length}</strong></td></tr>`}).join('')}</tbody></table>`}
function renderFields(day){const box=$('#gamesFieldCards');if(!box||!day)return;const enabled=new Set(matrix.fields||STANDARD_FIELDS);box.innerHTML=SETUPS.filter(x=>enabled.has(x.field)).map(x=>`<button type="button" class="games-field-card ${x.warn?'needs-change':''} ${x.critical?'critical-change':''}" data-field="${x.field}"><div class="games-field-title"><strong>${x.field}</strong>${x.champ?'<span>Championship</span>':x.warn?'<span>Setup Change</span>':'<span class="standard-badge">Standard</span>'}</div><h3>${x.division}</h3><div class="games-field-specs"><div><small>Pitching</small><b>${x.pitch}</b></div><div><small>Bases</small><b>${x.bases}</b></div></div><div class="games-field-day"><span>${fieldGameCount(day,x.field)} game${fieldGameCount(day,x.field)===1?'':'s'}</span><span>Next: ${nextFieldGame(day,x.field)}</span></div><p>${x.note}</p></button>`).join('')}
function renderAlerts(day){const box=$('#gamesOpsAlert');if(!box||!day)return;const live=(day.rows||[]).some((_,i)=>currentStatus(day,i)==='live');box.hidden=!live;box.innerHTML=live?'<div class="games-alert-icon">●</div><div><span>Games in progress</span><p>At least one scheduled time slot is currently active. Open the Operations Center for field-by-field status.</p></div>':''}
function renderOverview(){if(!matrix.days?.length)return;active=Math.min(active,matrix.days.length-1);const day=matrix.days[active];renderTabs();renderSummary(day);renderMatrix(day);renderFields(day);renderAlerts(day);window.dispatchEvent(new CustomEvent('ase:matrix-updated',{detail:matrix}))}

function cleanEditor(){
 if(!editor)return null;
 const fields=(editor.fields||[]).filter(f=>STANDARD_FIELDS.includes(f));
 const days=(editor.days||[])
  .filter(d=>d.key)
  .map(d=>{
   const meta=dayMeta(d.key);
   const rows=(d.rows||[])
    .filter(r=>r[0])
    .map(r=>[to12(to24(r[0])),(r[1]||[]).filter(f=>fields.includes(f))])
    .sort((a,b)=>to24(a[0]).localeCompare(to24(b[0])));
   return {...d,label:meta.label,short:meta.short,rows};
  })
  .filter(d=>d.rows.length)
  .sort((a,b)=>a.key.localeCompare(b.key));
 return {...editor,name:String(editor.name||'').trim()||'Tournament Field Matrix',fields,days,dateRange:dateRange(days)};
}
function validateEditor(){
 if(!editor?.days?.length)throw Error('Add at least one tournament date.');
 if(editor.days.some(d=>!d.key||!(d.rows||[]).length))throw Error('Every tournament day needs a date and at least one game time.');
 if(new Set(editor.days.map(d=>d.key)).size!==editor.days.length)throw Error('Each tournament date can only appear once.');
 if(editor.days.some(d=>(d.rows||[]).some(r=>!(r[1]||[]).length)))throw Error('Choose at least one field for every game time.');
 const x=cleanEditor();if(!x.fields.length)throw Error('Choose at least one field.');if(!x.days.length)throw Error('Add at least one tournament date and game time.');return x;
}
function blankMatrix(){const key=isoToday(),meta=dayMeta(key);return{id:`matrix-${Date.now()}`,name:'New Tournament Matrix',dateRange:'',fields:[...STANDARD_FIELDS],days:[{key,...meta,rows:[['9:00 AM',[]]]}],status:'draft',version:0}}
function setEditor(value){editor=clone(value||blankMatrix());if(!editor.fields?.length)editor.fields=[...STANDARD_FIELDS];if(!editor.days?.length){const b=blankMatrix();editor.days=b.days}editorDay=Math.min(editorDay,editor.days.length-1);dirty=false;renderEditor();markDirty(false)}
function renderLibrary(){const box=$('#gamesMatrixLibrary');if(!box)return;const all=library.length?library:[current];box.innerHTML=all.map(x=>`<button type="button" class="matrix-library-item ${editor?.id===x.id?'active':''}" data-matrix-id="${esc(x.id)}"><span><b>${esc(x.name||'Tournament Matrix')}</b><small>${esc(x.dateRange||'No dates')} · ${x.days?.length||0} day${x.days?.length===1?'':'s'}</small></span><em class="matrix-status ${x.id===current?.id?'live':'draft'}">${x.id===current?.id?'LIVE':'DRAFT'}</em></button>`).join('');$$('[data-matrix-id]',box).forEach(b=>b.onclick=()=>{const x=library.find(m=>m.id===b.dataset.matrixId)||current;if(dirty&&!confirm('Discard unsaved changes and open this matrix?'))return;setEditor(x)})}
function renderFieldSelector(){const box=$('#gamesEditorFields');if(!box)return;const selected=new Set(editor.fields||[]);box.innerHTML=STANDARD_FIELDS.map(f=>`<label class="matrix-field-toggle"><input type="checkbox" value="${f}" ${selected.has(f)?'checked':''}><span>${f}</span></label>`).join('');$$('input',box).forEach(input=>input.onchange=()=>{const next=$$('input:checked',box).map(x=>x.value);if(!next.length){input.checked=true;return notice('At least one field must stay selected.','error')}editor.fields=next;for(const d of editor.days)for(const r of d.rows)r[1]=r[1].filter(f=>next.includes(f));markDirty();renderDayEditor()})}
function renderEditorDayTabs(){const box=$('#gamesEditorDayTabs');if(!box)return;box.innerHTML=(editor.days||[]).map((d,i)=>`<button type="button" class="matrix-editor-day ${i===editorDay?'active':''}" data-editor-day="${i}"><b>${esc(d.label||dayMeta(d.key).label)}</b><small>${esc(d.key)}</small></button>`).join('');$$('button',box).forEach(b=>b.onclick=()=>{syncHeaderInputs();editorDay=Number(b.dataset.editorDay);renderEditor()})}
function syncHeaderInputs(){if(!editor)return;const name=$('#gamesEditorName');if(name)editor.name=name.value.trim()||editor.name;const date=$('#gamesEditorDate');if(date&&editor.days[editorDay]&&date.value){editor.days[editorDay].key=date.value;Object.assign(editor.days[editorDay],dayMeta(date.value))}}
function renderDayEditor(){const box=$('#gamesEditorSlots'),day=editor?.days?.[editorDay];if(!box||!day)return;box.innerHTML=(day.rows||[]).map((row,i)=>`<article class="matrix-slot-card" data-slot="${i}"><div class="matrix-slot-top"><label><span>Game time</span><input type="time" value="${to24(row[0])}" data-slot-time="${i}"></label><button type="button" class="danger-outline-btn compact-btn" data-remove-slot="${i}" aria-label="Remove game time">Remove</button></div><div class="matrix-slot-fields">${(editor.fields||[]).map(f=>`<label><input type="checkbox" data-slot-field="${i}" value="${f}" ${(row[1]||[]).includes(f)?'checked':''}><span>${f}</span></label>`).join('')}</div></article>`).join('')||'<div class="matrix-empty-editor"><b>No game times yet</b><p>Add a time to begin building this day.</p></div>';$$('[data-slot-time]',box).forEach(x=>x.onchange=()=>{day.rows[Number(x.dataset.slotTime)][0]=to12(x.value);day.rows.sort((a,b)=>to24(a[0]).localeCompare(to24(b[0])));markDirty();renderDayEditor()});$$('[data-slot-field]',box).forEach(x=>x.onchange=()=>{const row=day.rows[Number(x.dataset.slotField)],field=x.value;if(x.checked&&!row[1].includes(field))row[1].push(field);if(!x.checked)row[1]=row[1].filter(f=>f!==field);markDirty()});$$('[data-remove-slot]',box).forEach(x=>x.onclick=()=>{day.rows.splice(Number(x.dataset.removeSlot),1);markDirty();renderDayEditor()})}
function renderArchive(){const box=$('#gamesMatrixArchive');if(!box)return;box.innerHTML=archive.length?archive.slice(0,12).map(x=>`<div class="games-archive-item"><div><b>${esc(x.name||'Tournament Matrix')}</b><small>v${x.version||1} · ${x.updatedAt?new Date(x.updatedAt).toLocaleString():'Unknown date'}</small></div><button class="small-btn" data-restore="${esc(x.id)}" type="button">Publish Again</button></div>`).join(''):'<p class="empty-list">No archived schedules yet.</p>';$$('[data-restore]',box).forEach(b=>b.onclick=()=>restore(b.dataset.restore))}
function renderEditor(){if(!editor)return;const name=$('#gamesEditorName');if(name)name.value=editor.name||'';const date=$('#gamesEditorDate'),day=editor.days[editorDay];if(date)date.value=day?.key||'';const range=$('#gamesEditorRange');if(range)range.textContent=dateRange(editor.days);const live=$('#gamesEditorLiveLabel');if(live)live.hidden=editor.id!==current?.id;const del=$('#gamesDeleteMatrixButton');if(del)del.disabled=editor.id===current?.id;renderFieldSelector();renderEditorDayTabs();renderDayEditor();renderLibrary();renderArchive();const meta=$('#gamesManagerMeta');if(meta)meta.innerHTML=`<div><span>Days</span><strong>${editor.days.length}</strong></div><div><span>Games</span><strong>${editor.days.reduce((n,d)=>n+total(d),0)}</strong></div><div><span>Fields</span><strong>${editor.fields.length}</strong></div><div><span>Version</span><strong>v${editor.version||0}</strong></div>`}
function updateData(d){current=d.current||d.matrix||current;matrix=current;library=d.library||library;archive=d.archive||archive;active=todayIndex();renderOverview();if(editor){const refreshed=library.find(x=>x.id===editor.id)||current;setEditor(refreshed)}else setEditor(current)}

async function saveDraft(){try{syncHeaderInputs();const data=validateEditor(),b=$('#gamesSaveDraftButton');b.disabled=true;b.textContent='Saving…';const d=await apiPost({action:'save',matrix:data});library=d.library||library;archive=d.archive||archive;editor=d.matrix;dirty=false;renderEditor();markDirty(false);notice('Draft saved. It is not live until you publish it.','success')}catch(e){notice(e.message,'error')}finally{const b=$('#gamesSaveDraftButton');if(b){b.disabled=false;b.textContent='Save Draft'}}}
async function publish(){try{syncHeaderInputs();const data=validateEditor();if(!confirm(`Publish “${data.name}” live for ${data.dateRange}?`))return;const b=$('#gamesPublishMatrixButton');b.disabled=true;b.textContent='Publishing…';const d=await apiPost({action:'publish',matrix:data});current=d.current||d.matrix;matrix=current;library=d.library||library;archive=d.archive||archive;editor=clone(current);dirty=false;active=todayIndex();renderOverview();renderEditor();markDirty(false);notice('Matrix published live. Automatic schedule-change alerts will use this version.','success')}catch(e){notice(e.message,'error')}finally{const b=$('#gamesPublishMatrixButton');if(b){b.disabled=false;b.textContent='Publish Live'}}}
async function deleteMatrix(){if(!editor||editor.id===current?.id)return notice('The live matrix cannot be deleted. Publish another matrix first.','error');if(!confirm(`Delete “${editor.name}”? This cannot be undone.`))return;try{const d=await apiPost({action:'delete',id:editor.id});library=d.library||[];archive=d.archive||[];setEditor(library[0]||current);notice('Matrix deleted.','success')}catch(e){notice(e.message,'error')}}
async function restore(id){if(!confirm('Publish this archived schedule as the live matrix?'))return;try{const d=await apiPost({action:'restore',id});current=d.current||d.matrix;matrix=current;library=d.library||library;archive=d.archive||archive;setEditor(current);active=todayIndex();renderOverview();notice('Archived matrix published live.','success')}catch(e){notice(e.message,'error')}}
function newMatrix(){if(dirty&&!confirm('Discard unsaved changes and create a new matrix?'))return;editorDay=0;setEditor(blankMatrix())}
function addDay(){syncHeaderInputs();const last=editor.days.map(d=>d.key).sort().at(-1)||isoToday(),date=new Date(last+'T12:00:00Z');date.setUTCDate(date.getUTCDate()+1);const key=date.toISOString().slice(0,10),meta=dayMeta(key);editor.days.push({key,...meta,rows:[['9:00 AM',[]]]});editor.days.sort((a,b)=>a.key.localeCompare(b.key));editorDay=editor.days.findIndex(d=>d.key===key);markDirty();renderEditor()}
function copyPreviousDay(){syncHeaderInputs();if(editorDay<=0)return notice('There is no previous day to copy.','error');const prev=editor.days[editorDay-1],day=editor.days[editorDay];day.rows=clone(prev.rows);markDirty();renderDayEditor();notice(`${prev.label} game times copied to ${day.label}.`,'success')}
function deleteDay(){if(editor.days.length<=1)return notice('A matrix must keep at least one day.','error');const day=editor.days[editorDay];if(!confirm(`Remove ${day.label}, ${day.key} from this matrix?`))return;editor.days.splice(editorDay,1);editorDay=Math.max(0,editorDay-1);markDirty();renderEditor()}
function addSlot(){const day=editor.days[editorDay];day.rows.push(['9:00 AM',[]]);markDirty();renderDayEditor();setTimeout(()=>$$('[data-slot-time]',$('#gamesEditorSlots')).at(-1)?.focus(),10)}

function monthNumber(name){return['january','february','march','april','may','june','july','august','september','october','november','december'].indexOf(name.toLowerCase())+1}
function normalizeTime(v){const m=String(v).trim().match(/^(\d{1,2})(?::(\d{2}))?\s*(AM|PM)$/i);if(!m)return null;return`${Number(m[1])}:${String(m[2]||'00').padStart(2,'0')} ${m[3].toUpperCase()}`}
function parseText(text){const raw=String(text||'').replace(/\r/g,'').replace(/\u00a0/g,' ').trim();if(!raw)throw Error('Paste or upload a matrix first.');const lines=raw.split('\n').map(x=>x.trim()).filter(Boolean),parsed=[];let day=null,year=new Date().getFullYear();for(const line of lines){const dm=line.match(/^(MONDAY|TUESDAY|WEDNESDAY|THURSDAY|FRIDAY|SATURDAY|SUNDAY)\s*[•\-|]\s*(JANUARY|FEBRUARY|MARCH|APRIL|MAY|JUNE|JULY|AUGUST|SEPTEMBER|OCTOBER|NOVEMBER|DECEMBER)\s+(\d{1,2})(?:,\s*(\d{4}))?$/i);if(dm){year=Number(dm[4]||year);const key=`${year}-${String(monthNumber(dm[2])).padStart(2,'0')}-${String(Number(dm[3])).padStart(2,'0')}`,meta=dayMeta(key);day={key,...meta,rows:[]};parsed.push(day);continue}const tm=line.match(/^(\d{1,2}(?::\d{2})?\s*(?:AM|PM))\s+(.+)$/i);if(tm&&day){const time=normalizeTime(tm[1]),tokens=tm[2].split(/\s+/),active=[];STANDARD_FIELDS.forEach((f,i)=>{const mark=tokens[i];if(mark&&/^(✓|✔|x|yes|1)$/i.test(mark))active.push(f)});if(!active.length&&tokens.length>=8)STANDARD_FIELDS.forEach((f,i)=>{if(tokens[i]&&tokens[i]!=='—'&&tokens[i]!=='-')active.push(f)});day.rows.push([time,active])}}if(!parsed.length)throw Error('No day headings found. Use headings such as TUESDAY • JULY 28, 2026.');return{id:`matrix-${Date.now()}`,name:$('#gamesEditorName')?.value||'Imported Tournament Matrix',fields:[...STANDARD_FIELDS],days:parsed,status:'draft',version:0}}
async function importText(){try{const parsed=parseText($('#gamesMatrixText').value);$('#gamesMatrixPreview').innerHTML=`<div class="games-preview-stats"><div><strong>${parsed.days.length}</strong><small>Days</small></div><div><strong>${parsed.days.reduce((n,d)=>n+d.rows.length,0)}</strong><small>Times</small></div><div><strong>${parsed.days.reduce((n,d)=>n+total(d),0)}</strong><small>Games</small></div></div><p>${esc(dateRange(parsed.days))}</p>`;$('#gamesLoadImportButton').disabled=false;$('#gamesLoadImportButton')._parsed=parsed;notice('Import preview ready. Load it into the visual editor to review every day.','success')}catch(e){$('#gamesLoadImportButton').disabled=true;notice(e.message,'error')}}
async function handleFile(file){if(!file)return;$('#gamesMatrixFileName').textContent=file.name;try{let text='';if(/\.(xlsx|xls)$/i.test(file.name)){if(!window.XLSX)throw Error('Spreadsheet reader did not load. Save as CSV or TXT and try again.');const data=await file.arrayBuffer(),book=XLSX.read(data,{type:'array'}),sheet=book.Sheets[book.SheetNames[0]];text=XLSX.utils.sheet_to_csv(sheet,{FS:' '})}else text=await file.text();$('#gamesMatrixText').value=text;importText()}catch(e){notice(e.message,'error')}}

async function load(){try{const d=await request();current=d.matrix||FALLBACK;matrix=current;library=d.library||[current];archive=d.archive||[];canManage=Boolean(d.canManage||['owner','manager'].includes(role()));active=todayIndex();renderOverview();const manager=$('#gamesMatrixManager');if(manager)manager.hidden=!canManage;if(canManage)setEditor(current)}catch(e){matrix=current=FALLBACK;library=[current];active=todayIndex();renderOverview();console.warn(e)}}
function init(){if(!$('#gamesMatrix'))return;$('#gamesTodayButton')?.addEventListener('click',()=>{active=todayIndex();renderOverview()});$('#gamesNewMatrixButton')?.addEventListener('click',newMatrix);$('#gamesSaveDraftButton')?.addEventListener('click',saveDraft);$('#gamesPublishMatrixButton')?.addEventListener('click',publish);$('#gamesDeleteMatrixButton')?.addEventListener('click',deleteMatrix);$('#gamesAddDayButton')?.addEventListener('click',addDay);$('#gamesCopyDayButton')?.addEventListener('click',copyPreviousDay);$('#gamesDeleteDayButton')?.addEventListener('click',deleteDay);$('#gamesAddSlotButton')?.addEventListener('click',addSlot);$('#gamesEditorName')?.addEventListener('input',e=>{editor.name=e.target.value;markDirty()});$('#gamesEditorDate')?.addEventListener('change',e=>{if(!e.target.value)return;editor.days[editorDay].key=e.target.value;Object.assign(editor.days[editorDay],dayMeta(e.target.value));editor.days.sort((a,b)=>a.key.localeCompare(b.key));editorDay=editor.days.findIndex(d=>d.key===e.target.value);markDirty();renderEditor()});$('#gamesMatrixPreviewButton')?.addEventListener('click',importText);$('#gamesLoadImportButton')?.addEventListener('click',e=>{const parsed=e.currentTarget._parsed;if(!parsed)return;setEditor(parsed);markDirty();notice('Imported matrix loaded into the visual editor. Review it, save, or publish.','success')});$('#gamesMatrixFile')?.addEventListener('change',e=>handleFile(e.target.files?.[0]));window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
